### ISSUE TITLE
[Feature Request] Play Feedbacks in Edit Mode

### ISSUE THREAD

**Issue by digiwombat** [Juce-Assets/Juce-Feedbacks#11]
It would be nice to be able to see Feedbacks and UI tweens especially without having to go into play mode and would definitely speed up iteration times for me.

A sub-request here would be a Reset button or logic to set the sequence back to Frame 0 so that your objects could be reset since I believe the restart button currently replays the tween from initial positions.

**Comment by Guillemsc** [comment]
I just added the Reset functionality, and It's quite useful, thanks for the suggestion! :)

As for the preview feedbacks on edit mode, I don't think I it's a good idea to implement this (even if being able to play feedbacks on editor mode would be awesome). The principal issue is that playing a feedback could change the state of your game object, and then you would not be able to reset it to its original state because you are on edit mode. This is dangerous and could harm one's project. For now, I don't think It's worth the trouble. (I've had other people suggesting this, and it's been in my mind for a long time, it's not that I'm lazy, or I don't want to do it)
