### ISSUE TITLE
[Feature Request] A Feedbacks Manager and ID system for calling from code without GameObject references.

### ISSUE THREAD

**Issue by digiwombat** [Juce-Assets/Juce-Feedbacks#6]
While it's simple enough to write one, it would be nice to have an included class for managing and calling Feedbacks from inside my code without needing a reference to the gameobject the script lives on.

Ideally, it would allow for giving the Feedbacks script a string id and then provide either a singleton manager or something similar so you could do something like the following:

0. Add the FeedbacksManager to the scene.
1. Make a feedbacks sequence to do something (say show a UI).
2. Give it an id (e.g. ShowUI)
3. On awake the feedback adds itself to the manager's list of feedbacks
4. Call it from code with something like FeedbacksManager.Instance.PlayFeedbacks("ShowUI");

Obviously, it shouldn't require the Manager for people who want to handle their own stuff, but it would be a very convenient way for people to manage a larger number of feedbacks without having to write a manager for themselves.

EDIT: Thanks for the tool, man. It's useful and has some really nice editor design.

**Comment by Guillemsc** [comment]
Hey @digiwombat, first of all, thanks for reaching out, I'm glad you like the tool :D

On the feature request, It actually sounds like a very cool idea, that I did not thought about (since I always use direct references for almost everything), but your approach could be very useful on certain situations, or for people that don't like using direct references. 

I like the example that you proposed, but what would you think about, instead of doing `FeedbacksManager.Instance.PlayFeedbacks("ShowUI");` we do `FeedbacksManager.Instance.GetFeedback("ShowUI").Play();`? That way you can use directly all the functionality of the component, without relying on a generic function.

I will start working on this asap, and I will probably have this ready in 6-7 days.

**Comment by Guillemsc** [comment]
I also added a new category on the README.md with [upcoming features](https://github.com/Juce-Assets/Juce-Feedbacks#upcoming-features).

**Comment by Guillemsc** [comment]
As the development of the request was very small, the feature is already [here](https://github.com/Juce-Assets/Juce-Feedbacks/releases/latest) ready to use. A new version was also submitted to the AssetStore, and will ve available on the following 1-2 days. The documentation for this is still not ready, but if you want to try this out:

Select the new toggle on any FeedbacksPlayer named Used By Script, and set the id that you want
![image](https://user-images.githubusercontent.com/17142208/99822944-16851600-2b54-11eb-83f3-1a54a41aa747.png)

Then on the code, just do: (while using namespace Juce.Feedbacks)
`FeedbacksPlayer player = JuceFeedbacks.GetFeedbacksPlayer(id);`
or
`bool found = JuceFeedbacks.TryGetFeedbacksPlayer(id, out player))`
to get the FeedbacksPlayer component

and finally
`player.Play();`

Keep in mind that if you don't select the toggle Used By Script, you won't be able to get the FeedbacksPlayer from the code.

**Comment by Guillemsc** [comment]
Documentation [here](https://github.com/Juce-Assets/Juce-Feedbacks/wiki/Global-FeedbacksPlayers).

**Comment by digiwombat** [comment]
Awesome, man. Thanks for the quick work. :D This will definitely help for more complex state control with my many UI elements.

An unrelated aside: Sorry to see the weird anti-open source haters that seem to be following you around. If open source alternatives to commercial projects were somehow a bad thing, the entire scene wouldn't exist. Thanks again for the hard work.

**Comment by Guillemsc** [comment]
No problem! I hope you find it useful :)

I don't think there are any haters, I already recieved threats from the creator of MMFeedbacks, and my guess is that he's the only one sending me bad comments/reviews. But in the end, I really don't mind.

I'm closing this, since it's already resolved. If you find an issue or an improvement, you can open another issue.

Thank you very much for the contribution and the thoughts :)
